"""Application business logic for managing records.

The :class:`RecordManager` is the single object the GUI interacts with.
It owns the in-memory list of record dictionaries and exposes high-level
operations - create, update, delete, search, sort, statistics - that
keep the list consistent across record types.

By keeping all business rules in this class we can write fast,
GUI-independent unit tests against the manager.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Iterable

from .records import (
    AIRLINE,
    CLIENT,
    FLIGHT,
    RECORD_TYPES,
    build_airline_record,
    build_client_record,
    build_flight_record,
    next_id,
    validate_record,
)
from .storage import load_records, save_records

_LOGGER = logging.getLogger(__name__)


class RecordManager:
    """Manage the list of record dictionaries used by the application."""

    def __init__(
        self,
        records: list[dict[str, Any]] | None = None,
        storage_path: Path | str | None = None,
    ) -> None:
        self.records: list[dict[str, Any]] = list(records or [])
        self.storage_path: Path | None = Path(storage_path) if storage_path else None

        # Defensive validation: if a caller hands us records directly
        # (for example in unit tests) we still want every entry to
        # match the schema.
        for record in self.records:
            validate_record(record)

    # ------------------------------------------------------------------
    # Construction / persistence helpers
    # ------------------------------------------------------------------

    @classmethod
    def from_file(cls, storage_path: Path | str) -> "RecordManager":
        """Create a manager and load records from a JSON file."""

        return cls(load_records(storage_path), storage_path)

    def save(self) -> None:
        """Save records to the configured storage path."""

        if self.storage_path is None:
            raise ValueError("No storage path is configured.")
        save_records(self.storage_path, self.records)

    # ------------------------------------------------------------------
    # CRUD operations
    # ------------------------------------------------------------------

    def create_record(self, record_type: str, values: dict[str, Any]) -> dict[str, Any]:
        """Create a record and append it to the internal list."""

        record = self._build_record(record_type, values)
        self.records.append(record)
        _LOGGER.info("Created %s record.", record_type)
        return record

    def update_record(self, index: int, values: dict[str, Any]) -> dict[str, Any]:
        """Replace the record at the supplied list index."""

        existing = self.get_record(index)
        record_type = existing["Type"]

        # Client and airline IDs are immutable - they are generated by
        # the manager and other records may reference them, so we never
        # allow them to change on update.
        if record_type in (CLIENT, AIRLINE):
            values = {**values, "ID": existing["ID"]}

        replacement = self._build_record(record_type, values)
        self.records[index] = replacement
        _LOGGER.info("Updated %s record at index %d.", record_type, index)
        return replacement

    def delete_record(self, index: int) -> dict[str, Any]:
        """Delete and return the record at the supplied list index."""

        record = self.get_record(index)
        self._ensure_record_can_be_deleted(record)
        deleted = self.records.pop(index)
        _LOGGER.info("Deleted %s record from index %d.", record.get("Type"), index)
        return deleted

    def get_record(self, index: int) -> dict[str, Any]:
        """Return a record by list index."""

        if index < 0 or index >= len(self.records):
            raise IndexError("Record index is out of range.")
        return self.records[index]

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def list_records(
        self,
        record_type: str | None = None,
    ) -> list[tuple[int, dict[str, Any]]]:
        """Return records as ``(index, record)`` pairs.

        The optional ``record_type`` argument filters by type; the
        special value ``"All"`` or ``None`` returns every record.
        """

        return [
            (index, record)
            for index, record in enumerate(self.records)
            if record_type in (None, "All", record.get("Type"))
        ]

    def search_records(
        self,
        query: str = "",
        record_type: str | None = None,
    ) -> list[tuple[int, dict[str, Any]]]:
        """Search records by type and free-text across any field value."""

        query = str(query).strip().lower()
        matches: list[tuple[int, dict[str, Any]]] = []

        for index, record in self.list_records(record_type):
            if not query:
                matches.append((index, record))
                continue

            values = [str(value).lower() for value in record.values()]
            if any(query in value for value in values):
                matches.append((index, record))

        return matches

    def find_client(self, client_id: int) -> dict[str, Any] | None:
        """Return the client record with ``client_id`` if present."""

        return self._find_by_id(CLIENT, client_id)

    def find_airline(self, airline_id: int) -> dict[str, Any] | None:
        """Return the airline record with ``airline_id`` if present."""

        return self._find_by_id(AIRLINE, airline_id)

    def flights_for_client(self, client_id: int) -> list[dict[str, Any]]:
        """Return every flight record booked by ``client_id``."""

        return [
            record
            for record in self.records
            if record.get("Type") == FLIGHT and record.get("Client_ID") == client_id
        ]

    def flights_for_airline(self, airline_id: int) -> list[dict[str, Any]]:
        """Return every flight record using ``airline_id``."""

        return [
            record
            for record in self.records
            if record.get("Type") == FLIGHT and record.get("Airline_ID") == airline_id
        ]

    def statistics(self) -> dict[str, int]:
        """Return a small summary of the record counts by type."""

        stats = {CLIENT: 0, AIRLINE: 0, FLIGHT: 0}
        for record in self.records:
            record_type = record.get("Type")
            if record_type in stats:
                stats[record_type] += 1
        stats["Total"] = len(self.records)
        return stats

    def client_choices(self) -> list[tuple[int, str]]:
        """Return ``(id, label)`` pairs for combo-box population."""

        return [
            (record["ID"], f"#{record['ID']} {record.get('Name', '')}".strip())
            for record in self.records
            if record.get("Type") == CLIENT
        ]

    def airline_choices(self) -> list[tuple[int, str]]:
        """Return ``(id, label)`` pairs for combo-box population."""

        return [
            (record["ID"], f"#{record['ID']} {record.get('Company Name', '')}".strip())
            for record in self.records
            if record.get("Type") == AIRLINE
        ]

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_record(
        self,
        record_type: str,
        values: dict[str, Any],
    ) -> dict[str, Any]:
        """Build a record and run cross-record validation where needed."""

        if record_type == CLIENT:
            record_id = values.get("ID") or next_id(self.records, CLIENT)
            return build_client_record(values, record_id)

        if record_type == AIRLINE:
            record_id = values.get("ID") or next_id(self.records, AIRLINE)
            return build_airline_record(values, record_id)

        if record_type == FLIGHT:
            record = build_flight_record(values)
            self._validate_flight_references(record)
            return record

        valid_types = ", ".join(RECORD_TYPES)
        raise ValueError(f"Record type must be one of: {valid_types}.")

    def _validate_flight_references(self, record: dict[str, Any]) -> None:
        """Ensure a flight points to existing client and airline records."""

        if not self._record_id_exists(CLIENT, record["Client_ID"]):
            raise ValueError(
                f"Client_ID {record['Client_ID']} does not match any client record."
            )
        if not self._record_id_exists(AIRLINE, record["Airline_ID"]):
            raise ValueError(
                f"Airline_ID {record['Airline_ID']} does not match any airline record."
            )

    def _record_id_exists(self, record_type: str, record_id: int) -> bool:
        return any(
            record.get("Type") == record_type and record.get("ID") == record_id
            for record in self.records
        )

    def _find_by_id(self, record_type: str, record_id: int) -> dict[str, Any] | None:
        for record in self.records:
            if record.get("Type") == record_type and record.get("ID") == record_id:
                return record
        return None

    def _ensure_record_can_be_deleted(self, record: dict[str, Any]) -> None:
        """Block deletion of clients or airlines still referenced by flights."""

        record_type = record.get("Type")
        if record_type == CLIENT:
            field_name = "Client_ID"
        elif record_type == AIRLINE:
            field_name = "Airline_ID"
        else:
            return

        record_id = record.get("ID")
        is_referenced = any(
            item.get("Type") == FLIGHT and item.get(field_name) == record_id
            for item in self.records
        )
        if is_referenced:
            raise ValueError(
                f"Cannot delete {record_type.lower()} record while flights use it. "
                "Delete the related flight records first."
            )


def sort_records(
    records: Iterable[tuple[int, dict[str, Any]]],
    key: str,
    reverse: bool = False,
) -> list[tuple[int, dict[str, Any]]]:
    """Sort ``(index, record)`` pairs by a field name.

    Records missing the requested field are placed last regardless of
    sort direction so the GUI table never raises when the user clicks a
    column header for a field that does not exist on every record.
    """

    def sort_key(item: tuple[int, dict[str, Any]]):
        value = item[1].get(key, "")
        return (value is None or value == "", str(value).lower())

    return sorted(list(records), key=sort_key, reverse=reverse)
